### ISSUE TITLE
Game library

### ISSUE THREAD

**Issue by achristoforou1** [achristoforou1/love-running#8]
**User story**
As a Board Game Enthusiast, I want to explore a selection of featured board games on the website, so I can discover new games and decide which ones I might be interested in trying.

**Acceptance criteria**

- [x] Show four new games
- [x] Show four old favourites

**Tasks**

- [x] Show customers a range of games available in the shop
