### ISSUE TITLE
Reserve form

### ISSUE THREAD

**Issue by achristoforou1** [achristoforou1/love-running#9]
**User story**
As a family we enjoy being able to reserve and and book a specific game on a specific date and time thus ensuring there isn't any unnecessary waiting involved

**Acceptance criteria**

- [x] Reservation form on the game library page
- [x] Create booking form with game option, customer details, date, time and people for seating

**Tasks**

- [x] Create a  reservation form with fields for the user's name, contact information, preferred date and select which game they want to reserve.
